spring.application.name=gitInsideOut

spring.config.import=classpath:/secrets.properties 

spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=${db.username}
spring.neo4j.authentication.password=${db.password}

